### PR TITLE
Update mz.rb

### PR DESCRIPTION
**Pull request by joacoc**
New release v0.2.2

### CODE REVIEW

**Review by benesch — APPROVED** [review]

**Comment by joacoc** [comment]
@benesch Unfortunately, I can't merge in this repo. I will need you to press the merge button. Is this due to some SOC2-related issue, or may I inquire about it?

**Comment by benesch** [comment]
I have no idea! Can you send me a screenshot? I don't see anything in the repo settings that would prevent you from merging.

**Comment by joacoc** [comment]
@benesch yes! Here is: 
Screenshot 2023-10-03 at 11 12 03

**Comment by benesch** [comment]
Ah, thanks, I think I tracked it down. You should now be allowed to merge PRs after an approval.

**Pull request merged**
