### PR TITLE
Update for v0.2.1

### PR DESCRIPTION
**Pull request by quodlibetor**

### CODE REVIEW

**Comment by quodlibetor** [comment]
With this change the output of mkbottle looks like:

```console
$ NO_UPLOAD=y ./bin/mkbottle 0.2.1
==> curl -L https://downloads.mtrlz.dev/materialized-v0.2.1-x86_64-apple-darwin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.4M  100 14.4M    0     0  10.5M      0  0:00:01  0:00:01 --:--:-- 10.5M

Make sure these values are correct in Formula/materialized.rb:

url                'https://github.com/MaterializeInc/materialize/archive/v0.2.1.tar.gz'
sha256             'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
sha256             '5d2e58e5da8476b6dae46d06a2de1d4cde5b9b2ffa48e3853774c49a4b5efc06' => :high_sierra
STABLE_BUILD_SHA = "709f0ee4a4802de898fa30f71d733352d3b2ff94".freeze
```

**Comment by quodlibetor** [comment]
I've updated mkbottle to do the steps in order:

```console
$ ./bin/mkbottle 0.2.1
...
Make sure these values are correct in Formula/materialized.rb:

url                'https://github.com/MaterializeInc/materialize/archive/v0.2.1.tar.gz'
sha256             'b5b3770008051186c9ce88e3ddd8da0f2d646cd95dd65545eb9758893a84279e'
STABLE_BUILD_SHA = "709f0ee4a4802de898fa30f71d733352d3b2ff94".freeze
Update the formula and press enter when ready

==> curl ...
Created Bintray version
==> curl -n -f -T /Users/bwm/github/homebrew-materialize/materialized-0.2.1.high_sierra.bottle.tar.gz https://api.bintray.com/content/materialize/homebrew/materialized/0.2.1/materialized-0.2.1.high_sierra.bottle.tar.gz\;publish=1
{"message":"success"}
Uploaded and published bottle to Bintray
now put this in the Formula/materialized.rb

sha256             '3d2da523db055b709c4e5e56aa72f5b0910713ab9722ba72eb050bce9c6ecf5e' => :high_sierra
```

**Comment by benesch** [comment]
Hmm, it still seems like things are broken. Do you think we could maybe punt on the refactor to a non-release day? The `mkbottle` script is pretty finicky, and Brennan and I spent a lot of time getting it to work on both macOS and Linux and as part of GitHub CI. ISTM that maybe we could just upload a bottle based on the script as it exists on master, and then do the refactors off the critical path.

**Comment by quodlibetor** [comment]
yeah if this run doesn't work I'll do that

**Comment by quodlibetor** [comment]
Well this actually seems unrelated: 

```text
==> curl -L https://downloads.mtrlz.dev/materialized-v0.2.1-x86_64-apple-darwin.tar.gz 

curl: (22) The requested URL returned error: 403 rate limit exceeded
##[error]Process completed with exit code 22.
```

**Comment by benesch** [comment]
> Well this actually seems unrelated:

It seems like it might be related to the additional API requests that the script makes now?

**Comment by quodlibetor** [comment]
things interleaving stdout and stderr can be confusing

**Pull request closed without merging**
